bitexpert_sylius_forcelogin_admin_whitelist_entry_index:
  resource: |
    alias: bitexpert_sylius_forcelogin.whitelist_entry
    section: admin
    templates: "@SyliusAdmin\\shared\\crud"
    except: ['show']
    redirect: update
    grid: bitexpert_sylius_forcelogin_whitelist_entity
    form:
        type: BitExpert\SyliusForceCustomerLoginPlugin\Form\Type\WhitelistEntryType
  type: sylius.resource
