name: ci
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        dependencies: ['lowest', 'highest']
        symfony: ['^6.4', '^7.1']
        php-versions: ['8.2', '8.3', '8.4']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug
          extensions: bcmath, gd

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony }}"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Validate composer
        run: composer validate --strict

      - name: Check composer normalized
        run: composer normalize --dry-run

      - name: Validate package licenses
        run: composer check-license

      - name: Check code style
        run: composer cs-check

      - name: Check Twig style
        run: composer cs-twig

      - name: Static Code Analysis
        run: composer analyze

      - name: Unittests
        run: composer test
